name: ChatGlobo
version: '4.3'
main: com.masitasia.chatglobo.ChatGlobo
api-version: '1.21'
authors: [MasitasIA]
description: Muestra globos de texto automáticamente al chatear
commands:
  globo:
    description: Activa o desactiva tus propios globos
    usage: /globo
  globoglobal:
    description: Activa o desactiva el plugin para todos
    usage: /globoglobal
    permission: chatglobo.admin
  globoaltura:
    description: Ajusta la altura del globo
    usage: /globoaltura <numero>
    permission: chatglobo.admin
  globoclear:
    description: Limpia todos los globos activos
    usage: /globoclear
    permission: chatglobo.admin
  globomute:
    description: Silencia a un jugador para que no pueda usar globos
    usage: /globomute <jugador>
    permission: chatglobo.admin
  globotiempo:
    description: Ajusta el tiempo de duración de los globos
    usage: /globotiempo <segundos>
    permission: chatglobo.admin
  globospawn:
    description: Crea un globo donde estás mirando
    usage: /globospawn <texto>
    permission: chatglobo.admin
  globoreload:
    description: Recarga la configuración (config.yml)
    usage: /globoreload
    permission: chatglobo.admin
  globodelay:
    description: Ajusta el delay de aparición
    usage: /globodelay <ticks>
    permission: chatglobo.admin